
-- DROP THE ROLE IF IT EXISTS
DROP ROLE IF EXISTS POSTGRES;

-- CREATE THE ROLE WITH LOGIN PRIVILEGES
CREATE ROLE POSTGRES WITH LOGIN PASSWORD 'ETL';

-- GRANT THE NECESSARY PRIVILEGES ON THE DATABASE
GRANT CONNECT ON DATABASE POSTGRES TO POSTGRES;

-- CREATE THE SCHEMAS OLTP AND ESQ_SEQ AND ASSIGN OWNERSHIP TO POSTGRES
CREATE SCHEMA OLTP AUTHORIZATION POSTGRES;
CREATE SCHEMA ESQ_SEQ AUTHORIZATION POSTGRES;

-- GRANT SCHEMA PERMISSIONS
GRANT USAGE ON SCHEMA OLTP TO POSTGRES;
GRANT USAGE ON SCHEMA ESQ_SEQ TO POSTGRES;
GRANT CREATE ON SCHEMA OLTP TO POSTGRES;
GRANT CREATE ON SCHEMA ESQ_SEQ TO POSTGRES;

-- GRANT DATA MANIPULATION PERMISSIONS ON ALL TABLES IN THE SCHEMAS
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA OLTP TO POSTGRES;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ESQ_SEQ TO POSTGRES;

-- SET DEFAULT PRIVILEGES FOR FUTURE TABLES
ALTER DEFAULT PRIVILEGES IN SCHEMA OLTP GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO POSTGRES;
ALTER DEFAULT PRIVILEGES IN SCHEMA ESQ_SEQ GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO POSTGRES;

CREATE SCHEMA OLTP;
CREATE SCHEMA ESQ_SEQ;

CREATE SEQUENCE ESQ_SEQ.WEAPONS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 1000000 MINVALUE 1 ;
CREATE SEQUENCE ESQ_SEQ.CRIMES_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 1000000 MINVALUE 1 ;
CREATE SEQUENCE ESQ_SEQ.AGEGROUPS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 1000000 MINVALUE 1 ;
CREATE SEQUENCE ESQ_SEQ.DEPARTMENTS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 1000000 MINVALUE 1 ;
CREATE SEQUENCE ESQ_SEQ.TOWN_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 1000000 MINVALUE 1 ;
CREATE SEQUENCE ESQ_SEQ.FACT_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 10000000 MINVALUE 1 ;
CREATE SEQUENCE ESQ_SEQ.ARTICLE_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 1000000 MINVALUE 1 ;
CREATE SEQUENCE ESQ_SEQ.TIME_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 1000000 MINVALUE 1 ;
CREATE SEQUENCE ESQ_SEQ.GENDERS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 1000000 MINVALUE 1 ;

CREATE TABLE OLTP.WEAPONS(
    WEAPON_ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('ESQ_SEQ.WEAPONS_SEQ'),
    W_DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE OLTP.AGEGROUPS(
    AGEGROUP_ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('ESQ_SEQ.AGEGROUPS_SEQ'),
    AG_DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE OLTP.CRIMES(
    CRIME_ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('ESQ_SEQ.CRIMES_SEQ'),
    W_DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE OLTP.DEPARTMENTS(
    DEPARTMENT_ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('ESQ_SEQ.DEPARTMENTS_SEQ'),
    DEPARTMENT_NAME VARCHAR(20) NOT NULL,
    LATITUDE DECIMAL(10, 6),
    LONGITUDE DECIMAL(10, 6)
);


CREATE TABLE OLTP.TOWNS(
    TOWN_ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('ESQ_SEQ.TOWN_SEQ'),
    TOWN_NAME VARCHAR(50) NOT NULL,
    TOWN_FLAG INTEGER,
    LATITUDE DECIMAL(10, 6),
    LONGITUDE DECIMAL(10, 6)
);


CREATE TABLE OLTP.LOCATIONS(
    DANE_ID INTEGER PRIMARY KEY,
    DEPARTMENT_ID INT NOT NULL,
    TOWN_ID INT NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES OLTP.DEPARTMENTS(DEPARTMENT_ID),
    FOREIGN KEY (TOWN_ID) REFERENCES OLTP.TOWNS(TOWN_ID)
);

CREATE TABLE OLTP.ARTICLES (
    ARTICLE_ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('ESQ_SEQ.ARTICLE_SEQ'),
    ARTICLE_NAME VARCHAR(250) NOT NULL
);

CREATE TABLE OLTP.TIMES (
    TIME_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('ESQ_SEQ.TIME_SEQ'),
    DT_FECHA TIMESTAMP,
    NUM_ANIO INT,
    STR_SEMESTRE VARCHAR(20),
    NUM_PERIODO INT,
    STR_MES VARCHAR(20),
    NUM_MES INT,
    NUM_DIA INT,
    NUM_SEMANA_MES INT
);

CREATE TABLE OLTP.GENDERS (
	GENDER_ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('ESQ_SEQ.GENDERS_SEQ'),
	GENDER VARCHAR(50) NOT NULL
);

CREATE TABLE OLTP.HISTORIC(
    HISTORIC_ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('ESQ_SEQ.FACT_SEQ'),
    DANE_ID INTEGER NOT NULL,                     
    WEAPON_ID INTEGER NOT NULL,
    AGEGROUP_ID INTEGER NOT NULL,
    CRIME_ID INTEGER NOT NULL,
    ARTICLE_ID INTEGER NOT NULL,
    GENDER_ID INTEGER NOT NULL,
    TIME_ID BIGINT NOT NULL,--CREAR DIMENSION DE TIEMPO
    QUANTITY INT NOT NULL,
    FOREIGN KEY (DANE_ID) REFERENCES OLTP.LOCATIONS(DANE_ID),
    FOREIGN KEY (WEAPON_ID) REFERENCES OLTP.WEAPONS(WEAPON_ID),
    FOREIGN KEY (AGEGROUP_ID) REFERENCES OLTP.AGEGROUPS(AGEGROUP_ID),
    FOREIGN KEY (CRIME_ID) REFERENCES OLTP.CRIMES(CRIME_ID),
    FOREIGN KEY (ARTICLE_ID) REFERENCES OLTP.ARTICLES(ARTICLE_ID), 
    FOREIGN KEY (TIME_ID) REFERENCES OLTP.TIMES(TIME_ID),
	FOREIGN KEY (GENDER_ID) REFERENCES OLTP.GENDERS(GENDER_ID)
);